services:
  - type: psql
    name: url-shortener-db
    databaseName: url_shortener_db
    plan: free

  - type: web
    name: url-shortener-app
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: url-shortener-db
          property: connectionString
      - key: APP_KEY
        sync: false  # Set this manually in Render dashboard